// Catálogo del Manual de monstruos (D&D 5e, edición en castellano), sacado de su "Índice de perfiles".
// `page` es la página impresa del libro; en el PDF va corrida (ver MANUAL_PAGE_OFFSET).

export type Monster = { id: string; name: string; page: number }

/** Página impresa + esto = página del PDF (tapas e índice al principio). */
export const MANUAL_PAGE_OFFSET = 2

export const MONSTERS: Monster[] = [
  { id: "aarakocra", name: "Aarakocra", page: 12 },
  { id: "aboleth", name: "Aboleth", page: 13 },
  { id: "abominacion-yuan-ti", name: "Abominación yuan-ti", page: 310 },
  { id: "acechador-invisible", name: "Acechador invisible", page: 15 },
  { id: "acererak", name: "Acererak", page: 284 },
  { id: "acolito", name: "Acólito", page: 342 },
  { id: "aguila", name: "Águila", page: 319 },
  { id: "aguila-gigante", name: "Águila gigante", page: 319 },
  { id: "aguja-marchita", name: "Aguja marchita", page: 226 },
  { id: "alce", name: "Alce", page: 319 },
  { id: "alce-gigante", name: "Alce gigante", page: 319 },
  { id: "alfombra-asfixiante", name: "Alfombra asfixiante", page: 248 },
  { id: "alosaurio", name: "Alosaurio", page: 83 },
  { id: "androesfinge", name: "Androesfinge", page: 138 },
  { id: "ankheg", name: "Ankheg", page: 20 },
  { id: "anquilosaurio", name: "Anquilosaurio", page: 83 },
  { id: "aparicion", name: "Aparición", page: 21 },
  { id: "arana", name: "Araña", page: 320 },
  { id: "arana-de-fase", name: "Araña de fase", page: 320 },
  { id: "arana-gigante", name: "Araña gigante", page: 320 },
  { id: "arbol-despertado", name: "Árbol despertado", page: 321 },
  { id: "arbusto-despertado", name: "Arbusto despertado", page: 321 },
  { id: "arcanaloth", name: "Arcanaloth", page: 315 },
  { id: "archimago", name: "Archimago", page: 342 },
  { id: "arcipreste-kuo-toa", name: "Arcipreste kuo-toa", page: 210 },
  { id: "armadura-animada", name: "Armadura animada", page: 249 },
  { id: "arpia", name: "Arpía", page: 22 },
  { id: "asesino", name: "Asesino", page: 343 },
  { id: "avispa-gigante", name: "Avispa gigante", page: 321 },
  { id: "azer", name: "Azer", page: 23 },
  { id: "azotamentes", name: "Azotamentes", page: 25 },
  { id: "azotamentes-arcanista", name: "Azotamentes arcanista", page: 25 },
  { id: "babuino", name: "Babuino", page: 321 },
  { id: "balor", name: "Balor", page: 57 },
  { id: "bandido", name: "Bandido", page: 343 },
  { id: "banshee", name: "Banshee", page: 26 },
  { id: "barlgura", name: "Barlgura", page: 58 },
  { id: "baron-sahuagin", name: "Barón sahuagin", page: 278 },
  { id: "basilisco", name: "Basilisco", page: 27 },
  { id: "batidor", name: "Batidor", page: 344 },
  { id: "behir", name: "Behir", page: 28 },
  { id: "berserker", name: "Berserker", page: 344 },
  { id: "bestia-tremula", name: "Bestia trémula", page: 29 },
  { id: "bocon-barbotante", name: "Bocón barbotante", page: 30 },
  { id: "brote-miconido", name: "Brote micónido", page: 232 },
  { id: "broza-movediza", name: "Broza movediza", page: 31 },
  { id: "buho", name: "Búho", page: 322 },
  { id: "buho-gigante", name: "Búho gigante", page: 322 },
  { id: "buitre", name: "Buitre", page: 322 },
  { id: "buitre-gigante", name: "Buitre gigante", page: 322 },
  { id: "bulette", name: "Bulette", page: 32 },
  { id: "bullywug", name: "Bullywug", page: 33 },
  { id: "caballero", name: "Caballero", page: 345 },
  { id: "caballero-de-la-muerte", name: "Caballero de la muerte", page: 34 },
  { id: "caballero-githyanki", name: "Caballero githyanki", page: 171 },
  { id: "caballito-de-mar", name: "Caballito de mar", page: 322 },
  { id: "caballito-de-mar-gigante", name: "Caballito de mar gigante", page: 323 },
  { id: "caballo-de-guerra", name: "Caballo de guerra", page: 323 },
  { id: "caballo-de-guerra-esqueleto", name: "Caballo de guerra esqueleto", page: 143 },
  { id: "caballo-de-monta", name: "Caballo de monta", page: 323 },
  { id: "caballo-de-tiro", name: "Caballo de tiro", page: 323 },
  { id: "cabra", name: "Cabra", page: 323 },
  { id: "cabra-gigante", name: "Cabra gigante", page: 324 },
  { id: "calavera-llameante", name: "Calavera llameante", page: 35 },
  { id: "cambion", name: "Cambion", page: 36 },
  { id: "camello", name: "Camello", page: 324 },
  { id: "cangrejo", name: "Cangrejo", page: 324 },
  { id: "cangrejo-gigante", name: "Cangrejo gigante", page: 324 },
  { id: "capitan-bandido", name: "Capitán bandido", page: 345 },
  { id: "capitan-hobgoblin", name: "Capitán hobgoblin", page: 194 },
  { id: "carronero-reptante", name: "Carroñero reptante", page: 37 },
  { id: "caudillo-orco", name: "Caudillo orco", page: 255 },
  { id: "centauro", name: "Centauro", page: 38 },
  { id: "chacal", name: "Chacal", page: 324 },
  { id: "chaman-hombre-lagarto", name: "Chamán hombre lagarto", page: 198 },
  { id: "chasme", name: "Chasme", page: 59 },
  { id: "chillon", name: "Chillón", page: 201 },
  { id: "chuul", name: "Chuul", page: 39 },
  { id: "ciclope", name: "Cíclope", page: 40 },
  { id: "ciempies-gigante", name: "Ciempiés gigante", page: 324 },
  { id: "cieno-gris", name: "Cieno gris", page: 42 },
  { id: "cieno-gris-psiquico", name: "Cieno gris psíquico", page: 41 },
  { id: "ciervo", name: "Ciervo", page: 325 },
  { id: "cocatriz", name: "Cocatriz", page: 45 },
  { id: "cocodrilo", name: "Cocodrilo", page: 325 },
  { id: "cocodrilo-gigante", name: "Cocodrilo gigante", page: 325 },
  { id: "comadreja", name: "Comadreja", page: 325 },
  { id: "comadreja-gigante", name: "Comadreja gigante", page: 325 },
  { id: "contemplador", name: "Contemplador", page: 48 },
  { id: "contemplador-zombi", name: "Contemplador zombi", page: 318 },
  { id: "corrupto-yuan-ti", name: "Corrupto yuan-ti", page: 311 },
  { id: "couatl", name: "Couatl", page: 51 },
  { id: "cria-de-dragon-azul", name: "Cría de dragón azul", page: 91 },
  { id: "cria-de-dragon-blanco", name: "Cría de dragón blanco", page: 95 },
  { id: "cria-de-dragon-de-bronce", name: "Cría de dragón de bronce", page: 109 },
  { id: "cria-de-dragon-de-cobre", name: "Cría de dragón de cobre", page: 112 },
  { id: "cria-de-dragon-de-oro", name: "Cría de dragón de oro", page: 115 },
  { id: "cria-de-dragon-de-oropel", name: "Cría de dragón de oropel", page: 118 },
  { id: "cria-de-dragon-de-plata", name: "Cría de dragón de plata", page: 121 },
  { id: "cria-de-dragon-negro", name: "Cría de dragón negro", page: 98 },
  { id: "cria-de-dragon-rojo", name: "Cría de dragón rojo", page: 101 },
  { id: "cria-de-dragon-verde", name: "Cría de dragón verde", page: 105 },
  { id: "cuadron", name: "Cuadron", page: 239 },
  { id: "cubo-gelatinoso", name: "Cubo gelatinoso", page: 43 },
  { id: "cuervo", name: "Cuervo", page: 326 },
  { id: "dao", name: "Dao", page: 157 },
  { id: "demonio-de-las-sombras", name: "Demonio de las sombras", page: 66 },
  { id: "deva", name: "Deva", page: 17 },
  { id: "devorador-de-intelectos", name: "Devorador de intelectos", page: 68 },
  { id: "diablillo", name: "Diablillo", page: 73 },
  { id: "diablo-astado", name: "Diablo astado", page: 73 },
  { id: "diablo-barbado", name: "Diablo barbado", page: 74 },
  { id: "diablo-de-las-cadenas", name: "Diablo de las cadenas", page: 76 },
  { id: "diablo-de-la-sima", name: "Diablo de la sima", page: 75 },
  { id: "diablo-espinoso", name: "Diablo espinoso", page: 77 },
  { id: "diablo-gelido", name: "Diablo gélido", page: 78 },
  { id: "diablo-oseo", name: "Diablo óseo", page: 79 },
  { id: "diablo-punzante", name: "Diablo punzante", page: 80 },
  { id: "djinn", name: "Djinn", page: 158 },
  { id: "doppelganger", name: "Doppelganger", page: 85 },
  { id: "dracoliche-plantilla", name: "Dracoliche (plantilla)", page: 86 },
  { id: "dracoliche-azul-adulto", name: "Dracoliche azul adulto", page: 87 },
  { id: "dragon-azul-adulto", name: "Dragón azul adulto", page: 91 },
  { id: "dragon-azul-anciano", name: "Dragón azul anciano", page: 90 },
  { id: "dragon-azul-joven", name: "Dragón azul joven", page: 91 },
  { id: "dragon-blanco-adulto", name: "Dragón blanco adulto", page: 94 },
  { id: "dragon-blanco-anciano", name: "Dragón blanco anciano", page: 93 },
  { id: "dragon-blanco-joven", name: "Dragón blanco joven", page: 94 },
  { id: "dragon-de-bronce-adulto", name: "Dragón de bronce adulto", page: 108 },
  { id: "dragon-de-bronce-anciano", name: "Dragón de bronce anciano", page: 107 },
  { id: "dragon-de-bronce-joven", name: "Dragón de bronce joven", page: 108 },
  { id: "dragon-de-cobre-adulto", name: "Dragón de cobre adulto", page: 111 },
  { id: "dragon-de-cobre-anciano", name: "Dragón de cobre anciano", page: 110 },
  { id: "dragon-de-cobre-joven", name: "Dragón de cobre joven", page: 111 },
  { id: "dragon-de-oro-adulto", name: "Dragón de oro adulto", page: 114 },
  { id: "dragon-de-oro-anciano", name: "Dragón de oro anciano", page: 113 },
  { id: "dragon-de-oro-joven", name: "Dragón de oro joven", page: 115 },
  { id: "dragon-de-oropel-adulto", name: "Dragón de oropel adulto", page: 117 },
  { id: "dragon-de-oropel-anciano", name: "Dragón de oropel anciano", page: 116 },
  { id: "dragon-de-oropel-joven", name: "Dragón de oropel joven", page: 117 },
  { id: "dragon-de-plata-adulto", name: "Dragón de plata adulto", page: 120 },
  { id: "dragon-de-plata-anciano", name: "Dragón de plata anciano", page: 119 },
  { id: "dragon-de-plata-joven", name: "Dragón de plata joven", page: 121 },
  { id: "dragon-feerico", name: "Dragón feérico", page: 122 },
  { id: "dragon-negro-adulto", name: "Dragón negro adulto", page: 98 },
  { id: "dragon-negro-anciano", name: "Dragón negro anciano", page: 97 },
  { id: "dragon-negro-joven", name: "Dragón negro joven", page: 98 },
  { id: "dragon-rojo-adulto", name: "Dragón rojo adulto", page: 101 },
  { id: "dragon-rojo-anciano", name: "Dragón rojo anciano", page: 100 },
  { id: "dragon-rojo-joven", name: "Dragón rojo joven", page: 101 },
  { id: "dragon-sombrio-plantilla", name: "Dragón sombrío (plantilla)", page: 87 },
  { id: "dragon-sombrio-rojo-joven", name: "Dragón sombrío rojo joven", page: 88 },
  { id: "dragon-tortuga", name: "Dragón tortuga", page: 123 },
  { id: "dragon-verde-adulto", name: "Dragón verde adulto", page: 104 },
  { id: "dragon-verde-anciano", name: "Dragón verde anciano", page: 103 },
  { id: "dragon-verde-joven", name: "Dragón verde joven", page: 104 },
  { id: "drana", name: "Draña", page: 124 },
  { id: "dretch", name: "Dretch", page: 59 },
  { id: "driade", name: "Dríade", page: 125 },
  { id: "drow", name: "Drow", page: 132 },
  { id: "druida", name: "Druida", page: 346 },
  { id: "duende", name: "Duende", page: 126 },
  { id: "duergar", name: "Duergar", page: 127 },
  { id: "duodron", name: "Duodron", page: 238 },
  { id: "elefante", name: "Elefante", page: 326 },
  { id: "elemental-de-agua", name: "Elemental de agua", page: 129 },
  { id: "elemental-de-aire", name: "Elemental de aire", page: 129 },
  { id: "elemental-de-fuego", name: "Elemental de fuego", page: 130 },
  { id: "elemental-de-tierra", name: "Elemental de tierra", page: 130 },
  { id: "empireo", name: "Empíreo", page: 135 },
  { id: "engendro-vampirico", name: "Engendro vampírico", page: 305 },
  { id: "enjambre-de-aranas", name: "Enjambre de arañas", page: 328 },
  { id: "enjambre-de-avispas", name: "Enjambre de avispas", page: 328 },
  { id: "enjambre-de-ciempies", name: "Enjambre de ciempiés", page: 328 },
  { id: "enjambre-de-cuervos", name: "Enjambre de cuervos", page: 326 },
  { id: "enjambre-de-escarabajos", name: "Enjambre de escarabajos", page: 328 },
  { id: "enjambre-de-insectos", name: "Enjambre de insectos", page: 326 },
  { id: "enjambre-de-mordedores", name: "Enjambre de mordedores", page: 327 },
  { id: "enjambre-de-murcielagos", name: "Enjambre de murciélagos", page: 327 },
  { id: "enjambre-de-ratas", name: "Enjambre de ratas", page: 327 },
  { id: "enjambre-de-serpientes-venenosas", name: "Enjambre de serpientes venenosas", page: 327 },
  { id: "enredadera-marchita", name: "Enredadera marchita", page: 226 },
  { id: "ent", name: "Ent", page: 136 },
  { id: "erinia", name: "Erinia", page: 81 },
  { id: "escarabajo-de-fuego-gigante", name: "Escarabajo de fuego gigante", page: 328 },
  { id: "escorpion", name: "Escorpión", page: 328 },
  { id: "escorpion-gigante", name: "Escorpión gigante", page: 328 },
  { id: "espada-voladora", name: "Espada voladora", page: 249 },
  { id: "espantapajaros", name: "Espantapájaros", page: 140 },
  { id: "espectador", name: "Espectador", page: 49 },
  { id: "espectro", name: "Espectro", page: 141 },
  { id: "espia", name: "Espía", page: 346 },
  { id: "espora-de-gas", name: "Espora de gas", page: 201 },
  { id: "esqueleto", name: "Esqueleto", page: 142 },
  { id: "estirge", name: "Estirge", page: 144 },
  { id: "ettercap", name: "Ettercap", page: 145 },
  { id: "ettin", name: "Ettin", page: 146 },
  { id: "extrano-de-agua", name: "Extraño de agua", page: 147 },
  { id: "fantasma", name: "Fantasma", page: 148 },
  { id: "flumph", name: "Flumph", page: 149 },
  { id: "fomore", name: "Fomoré", page: 150 },
  { id: "fuego-fatuo", name: "Fuego fatuo", page: 151 },
  { id: "galeb-duhr", name: "Galeb duhr", page: 152 },
  { id: "gargola", name: "Gárgola", page: 153 },
  { id: "garra-reptante", name: "Garra reptante", page: 154 },
  { id: "gato", name: "Gato", page: 329 },
  { id: "gelatina-ocre", name: "Gelatina ocre", page: 42 },
  { id: "ghast", name: "Ghast", page: 189 },
  { id: "gigante-de-escarcha", name: "Gigante de escarcha", page: 166 },
  { id: "gigante-de-fuego", name: "Gigante de fuego", page: 167 },
  { id: "gigante-de-las-colinas", name: "Gigante de las colinas", page: 166 },
  { id: "gigante-de-las-nubes", name: "Gigante de las nubes", page: 167 },
  { id: "gigante-de-las-tormentas", name: "Gigante de las tormentas", page: 168 },
  { id: "gigante-de-piedra", name: "Gigante de piedra", page: 168 },
  { id: "ginoesfinge", name: "Ginoesfinge", page: 139 },
  { id: "glabrezu", name: "Glabrezu", page: 60 },
  { id: "gladiador", name: "Gladiador", page: 347 },
  { id: "gnoll", name: "Gnoll", page: 174 },
  { id: "gnoll-colmillo-de-yeenoghu", name: "Gnoll colmillo de Yeenoghu", page: 174 },
  { id: "gnomo-de-las-profundidades-svirfneblin", name: "Gnomo de las profundidades (svirfneblin)", page: 175 },
  { id: "goblin", name: "Goblin", page: 177 },
  { id: "golem-de-arcilla", name: "Gólem de arcilla", page: 179 },
  { id: "golem-de-carne", name: "Gólem de carne", page: 180 },
  { id: "golem-de-hierro", name: "Gólem de hierro", page: 181 },
  { id: "golem-de-piedra", name: "Gólem de piedra", page: 181 },
  { id: "gorgon", name: "Gorgon", page: 182 },
  { id: "goristro", name: "Goristro", page: 61 },
  { id: "grell", name: "Grell", page: 183 },
  { id: "grick", name: "Grick", page: 184 },
  { id: "grick-alfa", name: "Grick alfa", page: 184 },
  { id: "grifo", name: "Grifo", page: 185 },
  { id: "grimlock", name: "Grimlock", page: 186 },
  { id: "guardia", name: "Guardia", page: 347 },
  { id: "guardian-escudo", name: "Guardián escudo", page: 187 },
  { id: "guerrero-de-elite-drow", name: "Guerrero de élite drow", page: 132 },
  { id: "guerrero-githyanki", name: "Guerrero githyanki", page: 171 },
  { id: "guerrero-tribal", name: "Guerrero tribal", page: 347 },
  { id: "guiverno", name: "Guiverno", page: 188 },
  { id: "gul", name: "Gul", page: 189 },
  { id: "gusano-purpura", name: "Gusano púrpura", page: 190 },
  { id: "halcon", name: "Halcón", page: 329 },
  { id: "halcon-sangriento", name: "Halcón sangriento", page: 329 },
  { id: "hezrou", name: "Hezrou", page: 62 },
  { id: "hidra", name: "Hidra", page: 191 },
  { id: "hiena", name: "Hiena", page: 329 },
  { id: "hiena-gigante", name: "Hiena gigante", page: 329 },
  { id: "hipogrifo", name: "Hipogrifo", page: 192 },
  { id: "hobgoblin", name: "Hobgoblin", page: 194 },
  { id: "hombre-chacal", name: "Hombre chacal", page: 196 },
  { id: "hombre-jabali", name: "Hombre jabalí", page: 216 },
  { id: "hombre-lagarto", name: "Hombre lagarto", page: 197 },
  { id: "hombre-lobo", name: "Hombre lobo", page: 218 },
  { id: "hombre-oso", name: "Hombre oso", page: 215 },
  { id: "hombre-rata", name: "Hombre rata", page: 216 },
  { id: "hombre-tigre", name: "Hombre tigre", page: 217 },
  { id: "homunculo", name: "Homúnculo", page: 199 },
  { id: "hongo-violeta", name: "Hongo violeta", page: 201 },
  { id: "horror-acorazado", name: "Horror acorazado", page: 202 },
  { id: "horror-ganchudo", name: "Horror ganchudo", page: 203 },
  { id: "huargo", name: "Huargo", page: 330 },
  { id: "ifrit", name: "Ifrit", page: 159 },
  { id: "incubo", name: "Íncubo", page: 292 },
  { id: "jabali", name: "Jabalí", page: 330 },
  { id: "jabali-gigante", name: "Jabalí gigante", page: 330 },
  { id: "jefe-goblin", name: "Jefe goblin", page: 177 },
  { id: "jefe-osgo", name: "Jefe osgo", page: 257 },
  { id: "kenku", name: "Kenku", page: 204 },
  { id: "kobold", name: "Kobold", page: 205 },
  { id: "kobold-alado", name: "Kobold alado", page: 205 },
  { id: "kraken", name: "Kraken", page: 207 },
  { id: "kuo-toa", name: "Kuo-toa", page: 209 },
  { id: "lacero", name: "Lacero", page: 211 },
  { id: "lagarto", name: "Lagarto", page: 330 },
  { id: "lagarto-gigante", name: "Lagarto gigante", page: 331 },
  { id: "lamia", name: "Lamia", page: 212 },
  { id: "latigo-kuo-toa", name: "Látigo kuo-toa", page: 210 },
  { id: "lemur", name: "Lémur", page: 82 },
  { id: "leon", name: "León", page: 331 },
  { id: "liche", name: "Liche", page: 219 },
  { id: "lider-de-manada-gnoll", name: "Líder de manada gnoll", page: 174 },
  { id: "lobo", name: "Lobo", page: 331 },
  { id: "lobo-invernal", name: "Lobo invernal", page: 332 },
  { id: "lobo-terrible", name: "Lobo terrible", page: 332 },
  { id: "magmin", name: "Magmin", page: 221 },
  { id: "mago", name: "Mago", page: 347 },
  { id: "mago-drow", name: "Mago drow", page: 133 },
  { id: "mamut", name: "Mamut", page: 333 },
  { id: "manes", name: "Manes", page: 62 },
  { id: "manticora", name: "Mantícora", page: 222 },
  { id: "manto", name: "Manto", page: 223 },
  { id: "mantoscuro", name: "Mantoscuro", page: 224 },
  { id: "marid", name: "Marid", page: 160 },
  { id: "marilith", name: "Marilith", page: 63 },
  { id: "mastin", name: "Mastín", page: 333 },
  { id: "maton", name: "Matón", page: 348 },
  { id: "medusa", name: "Medusa", page: 227 },
  { id: "mephit-de-barro", name: "Mephit de barro", page: 228 },
  { id: "mephit-de-hielo", name: "Mephit de hielo", page: 228 },
  { id: "mephit-de-humo", name: "Mephit de humo", page: 229 },
  { id: "mephit-de-magma", name: "Mephit de magma", page: 229 },
  { id: "mephit-de-polvo", name: "Mephit de polvo", page: 230 },
  { id: "mephit-de-vapor", name: "Mephit de vapor", page: 230 },
  { id: "merrow", name: "Merrow", page: 231 },
  { id: "mezzoloth", name: "Mezzoloth", page: 315 },
  { id: "miconido-adulto", name: "Micónido adulto", page: 234 },
  { id: "mimeto", name: "Mimeto", page: 235 },
  { id: "minotauro", name: "Minotauro", page: 236 },
  { id: "minotauro-esqueleto", name: "Minotauro esqueleto", page: 143 },
  { id: "modron-renegado", name: "Modron renegado", page: 237 },
  { id: "mole-sombria", name: "Mole sombría", page: 240 },
  { id: "momia", name: "Momia", page: 242 },
  { id: "monje-githzerai", name: "Monje githzerai", page: 172 },
  { id: "monodron", name: "Monodron", page: 237 },
  { id: "monstruo-corrosivo", name: "Monstruo corrosivo", page: 244 },
  { id: "mordedores", name: "Mordedores", page: 333 },
  { id: "mula", name: "Mula", page: 333 },
  { id: "murcielago", name: "Murciélago", page: 334 },
  { id: "murcielago-gigante", name: "Murciélago gigante", page: 334 },
  { id: "naga-espiritual", name: "Naga espiritual", page: 246 },
  { id: "naga-guardiana", name: "Naga guardiana", page: 246 },
  { id: "naga-osea", name: "Naga ósea", page: 245 },
  { id: "nalfeshnee", name: "Nalfeshnee", page: 64 },
  { id: "noble", name: "Noble", page: 348 },
  { id: "notico", name: "Nótico", page: 247 },
  { id: "nycaloth", name: "Nycaloth", page: 316 },
  { id: "ogro", name: "Ogro", page: 250 },
  { id: "ogro-zombi", name: "Ogro zombi", page: 318 },
  { id: "oni", name: "Oni", page: 252 },
  { id: "orca", name: "Orca", page: 334 },
  { id: "orco", name: "Orco", page: 255 },
  { id: "orco-ojo-de-gruumsh", name: "Orco ojo de Gruumsh", page: 256 },
  { id: "orog", name: "Orog", page: 256 },
  { id: "osgo", name: "Osgo", page: 257 },
  { id: "oso-de-las-cavernas", name: "Oso de las cavernas", page: 334 },
  { id: "oso-lechuza", name: "Oso lechuza", page: 258 },
  { id: "oso-negro", name: "Oso negro", page: 334 },
  { id: "oso-pardo", name: "Oso pardo", page: 335 },
  { id: "oso-polar", name: "Oso polar", page: 334 },
  { id: "otyugh", name: "Otyugh", page: 259 },
  { id: "pantera", name: "Pantera", page: 335 },
  { id: "pegaso", name: "Pegaso", page: 260 },
  { id: "pentadron", name: "Pentadron", page: 239 },
  { id: "perforador", name: "Perforador", page: 261 },
  { id: "perro-del-inframundo", name: "Perro del inframundo", page: 335 },
  { id: "perro-intermitente", name: "Perro intermitente", page: 336 },
  { id: "peryton", name: "Peryton", page: 262 },
  { id: "pesadilla", name: "Pesadilla", page: 263 },
  { id: "pico-de-hacha", name: "Pico de hacha", page: 336 },
  { id: "pixie", name: "Pixie", page: 264 },
  { id: "planetar", name: "Planetar", page: 18 },
  { id: "plebeyo", name: "Plebeyo", page: 348 },
  { id: "plesiosaurio", name: "Plesiosaurio", page: 84 },
  { id: "poltergeist", name: "Poltergeist", page: 141 },
  { id: "poni", name: "Poni", page: 336 },
  { id: "pseudodragon", name: "Pseudodragón", page: 265 },
  { id: "pteranodon", name: "Pteranodon", page: 84 },
  { id: "pudin-negro", name: "Pudin negro", page: 44 },
  { id: "pulpo", name: "Pulpo", page: 336 },
  { id: "pulpo-gigante", name: "Pulpo gigante", page: 337 },
  { id: "quaggoth", name: "Quaggoth", page: 266 },
  { id: "quasit", name: "Quasit", page: 65 },
  { id: "quimera", name: "Quimera", page: 267 },
  { id: "rakshasa", name: "Rakshasa", page: 268 },
  { id: "rama-marchita", name: "Rama marchita", page: 226 },
  { id: "rana", name: "Rana", page: 337 },
  { id: "rana-gigante", name: "Rana gigante", page: 337 },
  { id: "rata", name: "Rata", page: 327 },
  { id: "rata-gigante", name: "Rata gigante", page: 338 },
  { id: "rata-gigante-enferma", name: "Rata gigante enferma", page: 338 },
  { id: "redivivo", name: "Redivivo", page: 269 },
  { id: "remorhaz", name: "Remorhaz", page: 270 },
  { id: "remorhaz-joven", name: "Remorhaz joven", page: 270 },
  { id: "renacuajo-slaad", name: "Renacuajo slaad", page: 288 },
  { id: "rey-reina-lagarto", name: "Rey/Reina lagarto", page: 198 },
  { id: "rinoceronte", name: "Rinoceronte", page: 338 },
  { id: "roc", name: "Roc", page: 271 },
  { id: "sabueso-infernal", name: "Sabueso infernal", page: 272 },
  { id: "sacerdote", name: "Sacerdote", page: 349 },
  { id: "sacerdotisa-de-lolth-drow", name: "Sacerdotisa de Lolth drow", page: 133 },
  { id: "sacerdotisa-sahuagin", name: "Sacerdotisa sahuagin", page: 278 },
  { id: "saga-cetrina", name: "Saga cetrina", page: 274 },
  { id: "saga-de-la-noche", name: "Saga de la noche", page: 275 },
  { id: "saga-de-los-mares", name: "Saga de los mares", page: 276 },
  { id: "sahuagin", name: "Sahuagin", page: 277 },
  { id: "salamandra", name: "Salamandra", page: 280 },
  { id: "sapo-gigante", name: "Sapo gigante", page: 338 },
  { id: "satiro", name: "Sátiro", page: 281 },
  { id: "sectario", name: "Sectario", page: 349 },
  { id: "sectario-fanatico", name: "Sectario fanático", page: 350 },
  { id: "semidragon-plantilla", name: "Semidragón (plantilla)", page: 282 },
  { id: "semidragon-rojo-veterano", name: "Semidragón rojo veterano", page: 282 },
  { id: "semiliche", name: "Semiliche", page: 283 },
  { id: "semiogro", name: "Semiogro", page: 251 },
  { id: "senor-de-la-guerra-hobgoblin", name: "Señor de la guerra hobgoblin", page: 195 },
  { id: "senor-de-las-momias", name: "Señor de las momias", page: 243 },
  { id: "serpiente-constrictora", name: "Serpiente constrictora", page: 338 },
  { id: "serpiente-constrictora-gigante", name: "Serpiente constrictora gigante", page: 339 },
  { id: "serpiente-de-fuego", name: "Serpiente de fuego", page: 279 },
  { id: "serpiente-venenosa", name: "Serpiente venenosa", page: 339 },
  { id: "serpiente-venenosa-gigante", name: "Serpiente venenosa gigante", page: 339 },
  { id: "serpiente-voladora", name: "Serpiente voladora", page: 339 },
  { id: "siervo-espora-plantilla", name: "Siervo espora (plantilla)", page: 232 },
  { id: "siervo-espora-quaggoth", name: "Siervo espora quaggoth", page: 232 },
  { id: "simio", name: "Simio", page: 339 },
  { id: "simio-gigante", name: "Simio gigante", page: 340 },
  { id: "sirenido", name: "Sirénido", page: 285 },
  { id: "slaad-azul", name: "Slaad azul", page: 288 },
  { id: "slaad-de-la-muerte", name: "Slaad de la muerte", page: 290 },
  { id: "slaad-gris", name: "Slaad gris", page: 289 },
  { id: "slaad-rojo", name: "Slaad rojo", page: 288 },
  { id: "slaad-verde", name: "Slaad verde", page: 289 },
  { id: "soberano-miconido", name: "Soberano micónido", page: 234 },
  { id: "solar", name: "Solar", page: 19 },
  { id: "sombra", name: "Sombra", page: 291 },
  { id: "sucubo", name: "Súcubo", page: 292 },
  { id: "tarantula-gigante", name: "Tarántula gigante", page: 340 },
  { id: "tarasca", name: "Tarasca", page: 294 },
  { id: "tejon", name: "Tejón", page: 340 },
  { id: "tejon-gigante", name: "Tejón gigante", page: 340 },
  { id: "thonot-quaggoth", name: "Thonot quaggoth", page: 266 },
  { id: "thri-kreen", name: "Thri-kreen", page: 296 },
  { id: "tiburon-cazador", name: "Tiburón cazador", page: 340 },
  { id: "tiburon-de-arrecife", name: "Tiburón de arrecife", page: 341 },
  { id: "tiburon-gigante", name: "Tiburón gigante", page: 341 },
  { id: "tigre", name: "Tigre", page: 341 },
  { id: "tigre-dientes-de-sable", name: "Tigre dientes de sable", page: 341 },
  { id: "tiranosaurio-rex", name: "Tiranosaurio rex", page: 84 },
  { id: "tirano-sepulcral", name: "Tirano sepulcral", page: 50 },
  { id: "triceratops", name: "Triceratops", page: 84 },
  { id: "tridron", name: "Tridron", page: 238 },
  { id: "troglodita", name: "Troglodita", page: 297 },
  { id: "troll", name: "Troll", page: 298 },
  { id: "tumulario", name: "Tumulario", page: 299 },
  { id: "uhroloth", name: "Uhroloth", page: 316 },
  { id: "unicornio", name: "Unicornio", page: 301 },
  { id: "vampiro", name: "Vampiro", page: 304 },
  { id: "veterano", name: "Veterano", page: 350 },
  { id: "vrock", name: "Vrock", page: 66 },
  { id: "xorn", name: "Xorn", page: 306 },
  { id: "yeti", name: "Yeti", page: 307 },
  { id: "yeti-abominable", name: "Yeti abominable", page: 308 },
  { id: "yochlol", name: "Yochlol", page: 67 },
  { id: "yuan-ti-purasangre", name: "Yuan-ti purasangre", page: 312 },
  { id: "zerth-githzerai", name: "Zerth githzerai", page: 172 },
  { id: "zombi", name: "Zombi", page: 318 },
]

const byId = new Map(MONSTERS.map((m) => [m.id, m]))
export const getMonster = (id: string | undefined) => (id ? byId.get(id) : undefined)

const fold = (s: string) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase()

/** Busca sin tildes ni mayúsculas; primero los que empiezan con el texto. */
export function searchMonsters(q: string): Monster[] {
  const f = fold(q.trim())
  if (!f) return MONSTERS
  const starts: Monster[] = []
  const has: Monster[] = []
  for (const m of MONSTERS) {
    const n = fold(m.name)
    if (n.startsWith(f)) starts.push(m)
    else if (n.includes(f)) has.push(m)
  }
  return [...starts, ...has]
}
