import type { AssetCategory } from './types'

// Nombres en castellano y correcciones de categoría. Lo que no esté acá usa la etiqueta generada.
export const LABELS: Record<string, string> = {
  Chair1x1: 'Silla',
  Pit1x1: 'Pozo',
  Pitcircle1x1: 'Pozo redondo',
  TableCircle1x1: 'Mesa redonda',
  arrow1x1: 'Flecha',
  barrel1x1: 'Barril',
  barreltwo1x1: 'Barril 2',
  bath1x2: 'Bañera',
  bed1x2: 'Cama',
  beddouble2x2: 'Cama doble',
  bedtwo1x2: 'Cama 2',
  bedtwodouble2x2: 'Cama doble 2',
  book1x1: 'Libro',
  bookcase1x1: 'Biblioteca',
  booktwo1x1: 'Libro 2',
  campfire1x1: 'Fogata',
  campfiretwo1x1: 'Fogata 2',
  chest1x1: 'Cofre',
  chesttwo1x1: 'Cofre 2',
  crate1x1: 'Cajón',
  cratetwo1x1: 'Cajón 2',
  door1x1: 'Puerta',
  doorflip1x1: 'Puerta (espejada)',
  doortransparent1x1: 'Puerta abierta',
  'doortransparentflip.1x1': 'Puerta abierta (espejada)',
  dresser1x1: 'Cómoda',
  effectsBlacksquare1x1: 'Sombra',
  effectsgradientlinear: 'Degradé lineal',
  effectsgradientradial: 'Degradé radial',
  effectsgradientradial2: 'Degradé radial 2',
  effectswhitesquare1x1: 'Luz',
  fire: 'Fuego',
  grasstile5x5: 'Pasto',
  hay1x1: 'Heno',
  hay2x2: 'Heno grande',
  opencrate1x1: 'Cajón abierto',
  'paper-pile1x1': 'Pila de papeles',
  paper1x1: 'Papel',
  pot1x1: 'Vasija',
  potplant1x1: 'Maceta',
  potplanttwo1x1: 'Maceta 2',
  sack1x1: 'Bolsa',
  sacktwo1x1: 'Bolsa 2',
  shelf1x1: 'Estante',
  stairs1x1: 'Escalera',
  stonytile5x5: 'Piedra',
  table1x1: 'Mesa',
  'table1x2-rough': 'Mesa larga rústica',
  table1x2: 'Mesa larga',
  tableCircleRough1x1: 'Mesa redonda rústica',
  tableCircleRough2x2: 'Mesa redonda rústica grande',
  tableRough1x1: 'Mesa rústica',
  tile5x5: 'Baldosa',
  toilet1x1: 'Inodoro',
  treasurepile1x1: 'Tesoro',
  treasurepile2x2: 'Tesoro grande',
  window1x1: 'Ventana',
  windowtwo1x1: 'Ventana 2',
}

export const CATEGORY_OVERRIDES: Record<string, AssetCategory> = {}

export const CATEGORY_LABELS: Record<AssetCategory, string> = {
  floor: 'Pisos',
  structure: 'Estructura',
  prop: 'Objetos',
  effect: 'Efectos',
  marker: 'Marcadores',
}
